### ISSUE TITLE
[EPIC] Comments UI improvements

### ISSUE THREAD

**Issue by msfjarvis** [msfjarvis/compose-lobsters#204]
Megathread for multiple UI/UX improvements we need to make for comments to be truly useful.

- [x] ~~HTML support~~ Fixed with #258 
- [x] ~~Reply button to add a comment to the post from the website~~ Fixed with #207, improved in #239
- [ ] Expand/collapse button in individual comments
- [ ] Possibly a button in each comment to get its link

**Comment by Skrilltrax** [comment]
For 2 & 4, I think we can add an icon on the header to open the comments URL and then maybe a gesture for opening each particular comment.

**Comment by msfjarvis** [comment]
> For 2 & 4, I think we can add an icon on the header to open the comments URL and then maybe a gesture for opening each particular comment.

For 2 I was thinking more along the lines of a FAB, for 4 I agree that a swipeable container is be a good option.
